repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: mixed-line-ending
      - id: detect-private-key

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        name: yamllint
        args: ['-c', 'ansible/.yamllint', 'ansible/']
        files: \.(yml|yaml)$

  - repo: local
    hooks:
      - id: ansible-lint
        name: ansible-lint
        entry: ansible-lint
        language: system
        files: \.(yml|yaml)$
        pass_filenames: false
        always_run: true
        args: ['-c', 'ansible/.ansible-lint', 'ansible/']
