#!/usr/bin/env zsh


if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS='zsh,ghostty,nvim,zellij,tmux,mise,opencode,bin'
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi


# Ensure stow target directories exist (some go under ~/.local/)
mkdir -p $HOME/.local/bin

for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo "stowing $folder"
    stow -D $folder
    stow $folder
done
