---
- name: Converge
  hosts: all
  become: true

  vars:
    dotfiles_user: "molecule"
    dotfiles_home: "/home/molecule"
    fonts_url: "https://github.com/JetBrains/JetBrainsMono/releases/download/v2.304/JetBrainsMono-2.304.zip"
    fonts_install_dir: "/home/molecule/.local/share/fonts"

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_facts['os_family'] == "Debian"

    - name: Create test user
      ansible.builtin.user:
        name: molecule
        shell: /bin/bash
        home: /home/molecule
        create_home: true

    - name: Install fontconfig and unzip
      ansible.builtin.apt:
        name:
          - fontconfig
          - unzip
        state: present
      when: ansible_facts['os_family'] == "Debian"

    - name: Change ownership
      ansible.builtin.file:
        path: /home/molecule
        state: directory
        recurse: true
        owner: molecule
        group: molecule
      changed_when: false

  roles:
    - role: fonts
      become: false
