[local]
localhost ansible_connection=local

[remote]
# Add your remote hosts here
# Example:
# myserver ansible_host=192.168.1.100 ansible_user=myuser
# webserver ansible_host=example.com ansible_user=ubuntu ansible_port=2222
ubuntu-test ansible_host=10.218.20.160 ansible_user=rnoh

[all:children]
local
remote

[all:vars]
ansible_python_interpreter=/usr/bin/python3
