---
- name: Converge
  hosts: all
  become: true

  vars:
    dotfiles_user: "molecule"
    dotfiles_home: "/home/molecule"
    dotfiles_repo: "/home/molecule/.dotfiles"

  pre_tasks:
    - name: Create test user
      ansible.builtin.user:
        name: molecule
        shell: /bin/bash
        home: /home/molecule
        create_home: true

    - name: Change ownership of home directory
      ansible.builtin.file:
        path: /home/molecule
        state: directory
        recurse: true
        owner: molecule
        group: molecule
        follow: no
      changed_when: false

  roles:
    - role: common
